/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as UnitsUnitIdAssessmentsAssessmentIdRouteImport } from './routes/units/$unitId/assessments/$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitIdAssessmentsAssessmentIdRoute =
  UnitsUnitIdAssessmentsAssessmentIdRouteImport.update({
    id: '/units/$unitId/assessments/$assessmentId',
    path: '/units/$unitId/assessments/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/units/$unitId/assessments/$assessmentId': typeof UnitsUnitIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/units/$unitId/assessments/$assessmentId': typeof UnitsUnitIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/units/$unitId/assessments/$assessmentId': typeof UnitsUnitIdAssessmentsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/sign-in' | '/units/$unitId/assessments/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/sign-in' | '/units/$unitId/assessments/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/units/$unitId/assessments/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  UnitsUnitIdAssessmentsAssessmentIdRoute: typeof UnitsUnitIdAssessmentsAssessmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$unitId/assessments/$assessmentId': {
      id: '/units/$unitId/assessments/$assessmentId'
      path: '/units/$unitId/assessments/$assessmentId'
      fullPath: '/units/$unitId/assessments/$assessmentId'
      preLoaderRoute: typeof UnitsUnitIdAssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  UnitsUnitIdAssessmentsAssessmentIdRoute:
    UnitsUnitIdAssessmentsAssessmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
